### PR TITLE
Create English version of Readme file (创建README英文版)

### PR DESCRIPTION
**Pull request by KTK27YT**
Using the info from the Chinese readme, I went ahead and translated it into English. It may not be as accurate as the Chinese version. as some words  aren't in the  dictionary . So , I have replaced them with the closest words in English.  根据README中文版,我翻译成英文，但系有啲字不系准确，因为英文不有呢个字。所以我使用最接近慨单词进行翻译

### CODE REVIEW

**Comment by hooke007** [comment]
这是中文本地化的项目，没有英语化的必要

**Comment by omaru-ok** [comment]
> Using the info from the Chinese readme, I went ahead and translated it into English. It may not be as accurate as the Chinese version. as some words aren't in the dictionary . So , I have replaced them with the closest words in English. 根据README中文版,我翻译成英文，但系有啲字不系准确，因为英文不有呢个字。所以我使用最接近慨单词进行翻译

yes bro .  i do not understand chinese . so please make it possible to in endlish too 🙏

**Comment by hooke007** [comment]
My repo’s index only shows the links to different docs.
mpv‘s mamual is the best ins of mpv. It’s meaningless to create the dup contents.

**Comment by omaru-ok** [comment]
> My repo’s index only shows the links to different docs. mpv‘s mamual is the best ins of mpv. It’s meaningless to create the dup contents.

i was mean to english version as the  English  version of mpv_lazy for the osc  in english that u have :( 
i want that

**Pull request closed without merging**
